### ISSUE TITLE
Large file management recommendation

### ISSUE THREAD

**Issue by daviddwlee84** [Dod-o/Statistical-Learning-Method_Code#1]
I found that you said the MNIST dataset was exceeded the maximum storage of the Github limitation.
Maybe you can try to use [`git-lfs`](https://git-lfs.github.com/) to manage that file then you won't need to keep the file in the different place!

**Comment by Dod-o** [comment]
I actually tried,but when I clone it I only got 1kb of dataset.
I will try again, thank you.

**Comment by Dod-o** [comment]
> 
> 
> I found that you said the MNIST dataset was exceeded the maximum storage of the Github limitation.
> Maybe you can try to use [`git-lfs`](https://git-lfs.github.com/) to manage that file then you won't need to keep the file in the different place!

I actually tried,but when I clone it I only got 1kb of dataset.
I will try again, thank you.

**Comment by daviddwlee84** [comment]
Maybe use `git lfs pull` to fetch lfs files. ([reference](https://github.com/git-lfs/git-lfs/issues/1161))
And it said that
> Git will only fetch LFS files that match patterns in your `.gitattributes`

Maybe another reason is that the file doesn't list in `.gitattributes`. Good luck :)

**Comment by Dod-o** [comment]
I was going to try it today, but I suddenly felt that if the dataSet was too large, it maybe very inconvenient to clone.
So I think it's better to maintain the data size, don't you think?
Best wishes
