### ISSUE TITLE
决策树算法中的一些问题

### ISSUE THREAD

**Issue by zhaoedf** [Dod-o/Statistical-Learning-Method_Code#10]
![image](https://user-images.githubusercontent.com/48846150/82200375-7c88aa80-9931-11ea-8e2c-dfaa2f9a7023.png)

关于这个部分的注释。从个人的学习和实际测试来看：a[0] = 1
并且一个关于numpy的特性是，对于一维的ndarray，".T"是不起作用的。
必须用reshape / transpose才能真正把一维改成二维（即矩阵）

当然了，这仅仅是我的看法和经验，所以希望和您探讨一下。

by the way，代码简洁，注释清晰，nice！

**Comment by zhaoedf** [comment]
![image](https://user-images.githubusercontent.com/48846150/82200736-f882f280-9931-11ea-9848-fedadb7108a6.png)
这是我的测试代码

**Comment by Dod-o** [comment]
已修改，感谢
