### ISSUE TITLE
感知机里算法的迭代问题

### ISSUE THREAD

**Issue by zxzyy10** [Dod-o/Statistical-Learning-Method_Code#3]
提问！感知机算法的实现里，对于判定条件的计算中，w初始化为一个1*n的向量，xi.T为n*1的向量，我们预期的结果应该是一个实数吧，如果使用numpy的*是不是有些不太合逻辑呢，是否考虑使用dot。

**Comment by Wangjj12777** [comment]
和楼上观点相同，最后决策函数的结果应该是一个数，如果用*的话，w*xi.T   得出来的是向量，无法与b相加，会导致报错
