### ISSUE TITLE
EM.py __main__中打印初始参数，顺序错了

### ISSUE THREAD

**Issue by Abel1802** [Dod-o/Statistical-Learning-Method_Code#7]
print('alpha0:%.1f, mu0:%.1f, sigmod0:%.1f, alpha1:%.1f, mu1:%.1f, sigmod1:%.1f' % (
        alpha0, alpha1, mu0 mu1, sigmod0, sigmod1
    ))

打印的名称与value不一致

**Comment by Dod-o** [comment]
done, thanks~
