### ISSUE TITLE
adaboost.py 空间划分

### ISSUE THREAD

**Issue by ren2504413601** [Dod-o/Statistical-Learning-Method_Code#8]
adaboost 中，div是不是对输入空间的切分？为什么代码中取值是 -0.5， 0.5， 1.5。输入空间不是二值化了，然后应该是0到1了

**Comment by Dod-o** [comment]
因为label只有0和1，所以可以定义3种划分点，一种小于0，一种在0-1之间，一种大于1。所以分别设置了-0.5，0.5和1.5

**Comment by ren2504413601** [comment]
看来还是自己理解的不深刻，多谢啦！
